# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='web',
  syntax='proto3',
  serialized_pb=_b('\n\ndemo.proto\x12\x03web\">\n\x0b\x44\x65moRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0b\n\x03\x65xt\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEMOREQUEST = _descriptor.Descriptor(
  name='DemoRequest',
  full_name='web.DemoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='web.DemoRequest.user_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='web.DemoRequest.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext', full_name='web.DemoRequest.ext', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['DemoRequest'] = _DEMOREQUEST

DemoRequest = _reflection.GeneratedProtocolMessageType('DemoRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEMOREQUEST,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:web.DemoRequest)
  ))
_sym_db.RegisterMessage(DemoRequest)


# @@protoc_insertion_point(module_scope)
